"""initial 12 tables

Revision ID: 2284b238e3d4
Revises:
Create Date: 2026-08-10 22:28:33.405339

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2284b238e3d4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("first_seen_ip", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("last_active_at", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("device_id"),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("idempotency_key", "device_id", "path"),
    )
    op.create_table(
        "api_keys",
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("encrypted_key", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("masked_key", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.device_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("device_id"),
    )
    op.create_table(
        "decks",
        sa.Column("deck_id", sa.String(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.device_id"],
        ),
        sa.PrimaryKeyConstraint("deck_id"),
    )
    op.create_index("ix_decks_device_updated", "decks", ["device_id", "updated_at"], unique=False)
    op.create_table(
        "pdf_files",
        sa.Column("file_id", sa.String(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.device_id"],
        ),
        sa.PrimaryKeyConstraint("file_id"),
    )
    op.create_index(
        "ix_pdf_files_device_created", "pdf_files", ["device_id", "created_at"], unique=False
    )
    op.create_table(
        "cards",
        sa.Column("card_id", sa.String(), nullable=False),
        sa.Column("deck_id", sa.String(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("front", sa.Text(), nullable=False),
        sa.Column("back", sa.Text(), nullable=False),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("card_type", sa.String(), nullable=False),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("statement", sa.Text(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("answer_boolean", sa.Integer(), nullable=True),
        sa.Column("generation_item_id", sa.String(), nullable=True),
        sa.Column("target_difficulty", sa.String(), nullable=True),
        sa.Column("knowledge_point_ids", sa.Text(), nullable=True),
        sa.Column("evidence_score", sa.Integer(), nullable=True),
        sa.Column("correctness_score", sa.Integer(), nullable=True),
        sa.Column("difficulty_score", sa.Integer(), nullable=True),
        sa.Column("learning_value_score", sa.Integer(), nullable=True),
        sa.Column("rubric_total_score", sa.Integer(), nullable=True),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["deck_id"], ["decks.deck_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("card_id"),
        sa.UniqueConstraint("deck_id", "position", name="uq_cards_deck_position"),
    )
    op.create_index("ix_cards_device_deck", "cards", ["device_id", "deck_id"], unique=False)
    op.create_index(
        "ix_cards_gen_item_partial",
        "cards",
        ["generation_item_id"],
        unique=True,
        sqlite_where=sa.text("source = 'GENERATED' AND generation_item_id IS NOT NULL"),
    )
    op.create_table(
        "chapters",
        sa.Column("chapter_id", sa.String(), nullable=False),
        sa.Column("file_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("start_page", sa.Integer(), nullable=False),
        sa.Column("end_page", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["pdf_files.file_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("chapter_id"),
    )
    op.create_index("ix_chapters_file_id", "chapters", ["file_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("file_id", sa.String(), nullable=True),
        sa.Column("deck_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("stage", sa.String(), nullable=True),
        sa.Column("selected_chapters", sa.Text(), nullable=False),
        sa.Column("generation_config", sa.Text(), nullable=False),
        sa.Column("cursor", sa.Text(), nullable=True),
        sa.Column("generated_card_count", sa.Integer(), nullable=False),
        sa.Column("total_batch_count", sa.Integer(), nullable=True),
        sa.Column("completed_batch_count", sa.Integer(), nullable=True),
        sa.Column("resumable", sa.Integer(), nullable=False),
        sa.Column("failure_stage", sa.String(), nullable=True),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("started_at", sa.String(), nullable=True),
        sa.Column("ended_at", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["deck_id"], ["decks.deck_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.device_id"],
        ),
        sa.ForeignKeyConstraint(["file_id"], ["pdf_files.file_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index("ix_tasks_device_created", "tasks", ["device_id", "created_at"], unique=False)
    op.create_index("ix_tasks_task_device", "tasks", ["task_id", "device_id"], unique=False)
    op.create_table(
        "batches",
        sa.Column("batch_id", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("batch_index", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("generated_item_ids", sa.Text(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("coverage_rate", sa.REAL(), nullable=True),
        sa.Column("duplicate_rate", sa.REAL(), nullable=True),
        sa.Column("difficulty_distribution", sa.Text(), nullable=True),
        sa.Column("chapter_distribution", sa.Text(), nullable=True),
        sa.Column("card_type_distribution", sa.Text(), nullable=True),
        sa.Column("difficulty_deviation", sa.REAL(), nullable=True),
        sa.Column("cache_hit_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_miss_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("request_id", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("schema_version", sa.String(), nullable=True),
        sa.Column("rubric_version", sa.String(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("ended_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("batch_id"),
        sa.UniqueConstraint("task_id", "batch_index", name="uq_batches_task_index"),
    )
    op.create_table(
        "knowledge_points",
        sa.Column("knowledge_point_id", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("chapter_id", sa.String(), nullable=True),
        sa.Column("source_chunk_id", sa.String(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("knowledge_point_id"),
    )
    op.create_index("ix_knowledge_points_task_id", "knowledge_points", ["task_id"], unique=False)
    op.create_table(
        "review_events",
        sa.Column("review_event_id", sa.String(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("card_id", sa.String(), nullable=False),
        sa.Column("client_event_id", sa.String(), nullable=False),
        sa.Column("rating", sa.String(), nullable=False),
        sa.Column("reviewed_at", sa.String(), nullable=False),
        sa.Column("device_timezone", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.card_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.device_id"],
        ),
        sa.PrimaryKeyConstraint("review_event_id"),
        sa.UniqueConstraint("device_id", "client_event_id", name="uq_review_events_device_client"),
    )
    op.create_index("ix_review_events_card_id", "review_events", ["card_id"], unique=False)
    op.create_index(
        "ix_review_events_device_reviewed",
        "review_events",
        ["device_id", "reviewed_at"],
        unique=False,
    )
    op.create_table(
        "review_states",
        sa.Column("review_state_id", sa.String(), nullable=False),
        sa.Column("card_id", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("stability", sa.REAL(), nullable=False),
        sa.Column("difficulty", sa.REAL(), nullable=False),
        sa.Column("due", sa.String(), nullable=False),
        sa.Column("last_review", sa.String(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("last_rating", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint(
            "difficulty >= 1 AND difficulty <= 10", name="ck_review_states_difficulty"
        ),
        sa.CheckConstraint("stability >= 0", name="ck_review_states_stability"),
        sa.ForeignKeyConstraint(["card_id"], ["cards.card_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("review_state_id"),
        sa.UniqueConstraint("card_id"),
    )
    op.create_index("ix_review_states_due", "review_states", ["due"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_review_states_due", table_name="review_states")
    op.drop_table("review_states")
    op.drop_index("ix_review_events_device_reviewed", table_name="review_events")
    op.drop_index("ix_review_events_card_id", table_name="review_events")
    op.drop_table("review_events")
    op.drop_index("ix_knowledge_points_task_id", table_name="knowledge_points")
    op.drop_table("knowledge_points")
    op.drop_table("batches")
    op.drop_index("ix_tasks_task_device", table_name="tasks")
    op.drop_index("ix_tasks_device_created", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_chapters_file_id", table_name="chapters")
    op.drop_table("chapters")
    op.drop_index(
        "ix_cards_gen_item_partial",
        table_name="cards",
        sqlite_where=sa.text("source = 'GENERATED' AND generation_item_id IS NOT NULL"),
    )
    op.drop_index("ix_cards_device_deck", table_name="cards")
    op.drop_table("cards")
    op.drop_index("ix_pdf_files_device_created", table_name="pdf_files")
    op.drop_table("pdf_files")
    op.drop_index("ix_decks_device_updated", table_name="decks")
    op.drop_table("decks")
    op.drop_table("api_keys")
    op.drop_table("idempotency_keys")
    op.drop_table("devices")
    # ### end Alembic commands ###
